apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: app-ingress
  namespace: {{.Values.nameSpace}}
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /student
            backend:
              serviceName: {{.Values.studentHostName}}
              servicePort: 8080
