apiVersion: v1
kind: Service
metadata:
  name: "{{.Values.resultsAtomizentHostName}}"
  namespace: "{{.Values.nameSpace}}"
spec:
  type: LoadBalancer
  ports:
    - port: 8090
      targetPort: {{.Values.resultsAtomizetAppPort}}
  selector:
    app: results-atomize