apiVersion: v1
kind: Service
metadata:
  name: "{{.Values.studentHostName}}"
  namespace: "{{.Values.nameSpace}}"
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: {{.Values.studentAppPort}}
  selector:
    app: student