apiVersion: v1
kind: Service
metadata:
  name: "{{.Values.videoEditorHostName}}"
  namespace: "{{.Values.nameSpace}}"
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: student