apiVersion: apps/v1
kind: Deployment
metadata:
  name: results-atomize
  namespace: "{{.Values.nameSpace}}"
  labels:
    app: results-atomize
spec:
  replicas: 1
  selector:
    matchLabels:
      app: results-atomize
  template:
    metadata:
      labels:
        app: results-atomize
    spec:
      containers:
        - image: einavl/{{.Values.resultsAtomizetAppName}}:{{.Values.resultsAtomizentVersion}}
          name: results-atomize
          ports:
            - containerPort: {{.Values.resultsAtomizetAppPort}}